version: '3.7'
services:
    webserver:
        build: .
        #image: 773527540682.dkr.ecr.us-east-1.amazonaws.com/ecr-airflow:prod #puckel/docker-airflow:1.10.9
        restart: always
        env_file: .envaws
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - /tmp
            - /raw_tmp
        ports:
            - "8080:8080"
        command: webserver -p 8080 -D True
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3 